
const Images = {
	ic_logo: require("@/assets/ic_logo.png"),
	ic_grapic1: require("@/assets/ic_grapic1.png"),
	ic_grapic2: require("@/assets/ic_grapic2.png"),
	ic_grapic3: require("@/assets/ic_grapic3.png"),
	ic_grapic4: require("@/assets/ic_grapic4.png"),
	ic_google: require("@/assets/ic_google.png"),
	ic_calendar: require("@/assets/ic_calendar.png"),
	ic_contact: require("@/assets/ic_contact.png"),
	ic_dashboard: require("@/assets/ic_dashboard.png"),
	ic_dollar: require("@/assets/ic_dollar.png"),
	ic_search: require("@/assets/ic_search.png"),
	ic_task_checked: require("@/assets/ic_task_checked.png"),
	ic_ticket: require("@/assets/ic_ticket.png"),
	ic_settings: require("@/assets/ic_settings.png"),
	ic_calendar_white: require("@/assets/ic_calendar_white.png"),
	ic_contact_white: require("@/assets/ic_contact_white.png"),
	ic_dashboard_white: require("@/assets/ic_dashboard_white.png"),
	ic_dollar_white: require("@/assets/ic_dollar_white.png"),
	ic_search_white: require("@/assets/ic_search_white.png"),
	ic_task_checked_white: require("@/assets/ic_task_checked_white.png"),
	ic_ticket_white: require("@/assets/ic_ticket_white.png"),
	ic_settings_white: require("@/assets/ic_settings_white.png"),
	ic_chevron_up: require("@/assets/ic_chevron_up.png"),
	ic_chevron_down: require("@/assets/ic_chevron_down.png"),
	ic_chevron_up_white: require("@/assets/ic_chevron_up_white.png"),
	ic_chevron_down_white: require("@/assets/ic_chevron_down_white.png"),
	ic_book: require("@/assets/ic_book.png"),
	ic_book_white: require("@/assets/ic_book_white.png"),
	ic_plus: require("@/assets/ic_plus.png"),
	ic_bank: require("@/assets/ic_bank.png"),
	ic_cheque: require("@/assets/ic_cheque.png"),
	ic_call: require("@/assets/ic_call.png"),
	ic_organization: require("@/assets/ic_organization.png"),
	ic_inbound_call: require("@/assets/ic_inbound_call.png"),
	ic_outbound_call: require("@/assets/ic_outbound_call.png"),
	ic_sms_purple: require("@/assets/ic_sms_purple.png"),
	ic_chat_yellow: require("@/assets/ic_chat_yellow.png"),
	ic_email_blue: require("@/assets/ic_email_blue.png"),
	ic_duplicate_orange: require("@/assets/ic_duplicate_orange.png"),
	ic_placeholder: require("@/assets/ic_placeholder.jpg"),
	ic_inquired_blue: require("@/assets/ic_inquired_blue.png"),
	ic_eye_hidden: require("@/assets/ic_eye_hidden.png"),
	ic_eye_show: require("@/assets/ic_eye_show.png"),
	ic_arrow_curl_up: require("@/assets/ic_arrow_curl_up.png"),
	ic_like_orange: require("@/assets/ic_like_orange.png"),
	ic_cash_app: require("@/assets/ic_cash_app.png"),
	ic_ach: require("@/assets/ic_ach.png"),
	ic_cash: require("@/assets/ic_cash.png"),
	ic_bank_check: require("@/assets/ic_bank_check.png"),
	ic_paypal: require("@/assets/ic_paypal.png"),
	ic_google_pay: require("@/assets/ic_google_pay.png"),
	ic_apple_pay: require("@/assets/ic_apple_pay.png"),
	ic_discover: require("@/assets/ic_discover.png"),
	ic_american_express: require("@/assets/ic_american_express.png"),
	ic_mastercard: require("@/assets/ic_mastercard.png"),
	ic_visa: require("@/assets/ic_visa.png"),
	ic_share: require("@/assets/ic_share.png"),

	ic_call_green: require("@/assets/ic_call_green.png"),
	ic_call_grey: require("@/assets/ic_call_grey.png"),
	ic_chat_grey: require("@/assets/ic_chat_grey.png"),
	ic_sms_grey: require("@/assets/ic_sms_grey.png"),
	ic_email_grey: require("@/assets/ic_email_grey.png"),


	ic_spreadsheets: require("@/assets/ic_spreadsheets.png"),
	ic_groups_half_black: require("@/assets/ic_groups_half_black.png"),
	ic_contacts_book_black: require("@/assets/ic_contacts_book_black.png"),
	ic_csv: require("@/assets/ic_csv.png"),


	ic_unordered_list: require("@/assets/ic_unordered_list.png"),
	ic_ordered_list: require("@/assets/ic_ordered_list.png"),
	ic_blockquote: require("@/assets/ic_blockquote.png"),
	ic_table: require("@/assets/ic_table.png"),
	ic_table_borderless: require("@/assets/ic_table_borderless.png"),
	ic_play_button_grey: require("@/assets/ic_play_button_grey.png"),

	ic_notification: require("@/assets/ic_notification.png"),
	ic_notification_active: require("@/assets/ic_notification_active.png"),
	ic_canoe: require("@/assets/ic_canoe.png"),
	ic_paintball: require("@/assets/ic_paintball.png"),
	ic_pool: require("@/assets/ic_pool.png"),
	ic_zipline: require("@/assets/ic_zipline.png"),

	ic_cc_arrow: require("@/assets/ic_cc_arrow.png"),
	ic_cc_arrow_white: require("@/assets/ic_cc_arrow_white.png"),
	ic_group: require("@/assets/ic_group.png"),
	ic_group_white: require("@/assets/ic_group_white.png"),
	ic_upload: require("@/assets/ic_upload.png"),
	ic_upload_white: require("@/assets/ic_upload_white.png"),
	ic_clip: require("@/assets/ic_clip.png"),
	ic_setup: require("@/assets/ic_setup.png"),
	ic_staff_id: require("@/assets/ic_staff_id.png"),
	ic_camp: require("@/assets/ic_camp.png"),
	ic_setup_white: require("@/assets/ic_setup_white.png"),
	ic_staff_id_white: require("@/assets/ic_staff_id_white.png"),
	ic_camp_white: require("@/assets/ic_camp_white.png"),
	ic_back: require("@/assets/ic_back.png"),
	ic_back_white: require("@/assets/ic_back_white.png"),
	ic_edit_black: require("@/assets/ic_edit_black.png"),
	ic_edit_gray: require("@/assets/ic_edit_gray.png"),
	ic_location: require("@/assets/ic_location.png"),
	ic_clock: require("@/assets/ic_clock.png"),
	ic_user_fill: require("@/assets/ic_user_fill.png"),
	ic_check: require("@/assets/ic_check.png"),
	ic_close: require("@/assets/ic_close.png"),
	ic_check_green: require("@/assets/ic_check_green.png"),
	ic_close_red: require("@/assets/ic_close_red.png"),
	ic_info: require("@/assets/ic_info.png"),
	ic_merge: require("@/assets/ic_merge.png"),
	ic_download: require("@/assets/ic_download.png"),
	ic_delete: require("@/assets/ic_delete.png"),
	ic_delete_red: require("@/assets/ic_delete_red.png"),
	ic_envelop: require("@/assets/ic_envelop.png"),
	ic_text_bubble: require("@/assets/ic_text_bubble.png"),
	ic_night: require("@/assets/ic_night.png"),
	ic_day: require("@/assets/ic_day.png"),
	ic_food_utensils: require("@/assets/ic_food_utensils.png"),
	ic_phone: require("@/assets/ic_phone.png"),
	ic_microphone: require("@/assets/ic_microphone.png"),
	ic_microphone_mute: require("@/assets/ic_microphone_mute.png"),
	ic_incoming_call: require("@/assets/ic_incoming_call.png"),
	ic_outgoing_call: require("@/assets/ic_outgoing_call.png"),
	ic_doc: require("@/assets/ic_doc.png"),
	ic_doc_white: require("@/assets/ic_doc_white.png"),
	ic_event: require("@/assets/ic_event.png"),
	ic_event_white: require("@/assets/ic_event_white.png"),
	ic_tent: require("@/assets/ic_tent.png"),
	ic_media: require("@/assets/ic_media.png"),
	ic_mail_check: require("@/assets/ic_mail_check.png"),
	ic_download_on_the_play_store: require("@/assets/ic_download_on_the_play_store.png"),
	ic_download_on_the_app_store: require("@/assets/ic_download_on_the_app_store.png"),
	ic_copy: require("@/assets/ic_copy.png"),
	ic_check_green_thick: require("@/assets/ic_check_green_thick.png"),
	ic_facebook: require("@/assets/ic_facebook.png"),
	ic_instagram: require("@/assets/ic_instagram.png"),
	ic_twitter: require("@/assets/ic_twitter.png"),
	ic_send_btn: require("@/assets/ic_send_btn.png"),
	ic_edoc_signed: require("@/assets/ic_edoc_signed.png"),
	ic_edoc_warning: require("@/assets/ic_edoc_warning.png"),
	ic_location_pin: require("@/assets/ic_location_pin.png"),
	gif_location_pin: require("@/assets/gif_location_pin.gif"),
	gif_loading: require("@/assets/gif_loading.gif"),
	ic_sunrise: require("@/assets/ic_sunrise.png"),
	ic_sunset: require("@/assets/ic_sunset.png"),
	ic_loading: require("@/assets/ic_loading.png"),
	ic_checkin: require("@/assets/ic_checkin.png"),
	ic_checkout: require("@/assets/ic_checkout.png"),
	ic_in_the_works: require("@/assets/ic_in_the_works.png"),
	ic_coming_soon: require("@/assets/ic_coming_soon.png"),
	ic_check_gradient_green: require("@/assets/ic_check_gradient_green.png"),
	ic_privacy_policy: require("@/assets/ic_privacy_policy.png"),
	ic_terms_of_service: require("@/assets/ic_terms_of_service.png"),
	ic_expand: require("@/assets/ic_expand.png"),
	ic_itinerary: require("@/assets/ic_itinerary.png"),
	ic_gallery_placeholder: require("@/assets/ic_gallery_placeholder.png"),

	ic_checklist_blue: require("@/assets/ic_checklist_blue.png"),
	ic_add_user_grey: require("@/assets/ic_add_user_grey.png"),
	ic_three_dots: require("@/assets/ic_three_dots.png"),
	ic_six_dots_grey: require("@/assets/ic_six_dots_grey.png"),

	ic_booked_stage: require("@/assets/ic_booked_stage.png"),
	ic_communicating_stage: require("@/assets/ic_communicating_stage.png"),
	ic_contacted_stage: require("@/assets/ic_contacted_stage.png"),
	ic_contract_sent_stage: require("@/assets/ic_contract_sent_stage.png"),
	ic_contract_signed_stage: require("@/assets/ic_contract_signed_stage.png"),
	ic_inquired_stage: require("@/assets/ic_inquired_stage.png"),
	ic_lost_stage: require("@/assets/ic_lost_stage.png"),
	ic_non_responsive_stage: require("@/assets/ic_non_responsive_stage.png"),
	ic_waiting_list_stage: require("@/assets/ic_waiting_list_stage.png"),

	ic_booked_white: require("@/assets/ic_booked_white.png"),
	ic_communicating_white: require("@/assets/ic_communicating_white.png"),
	ic_contacted_white: require("@/assets/ic_contacted_white.png"),
	ic_contract_sent_white: require("@/assets/ic_contract_sent_white.png"),
	ic_contract_signed_white: require("@/assets/ic_contract_signed_white.png"),
	ic_inquired_white: require("@/assets/ic_inquired_white.png"),
	ic_lost_white: require("@/assets/ic_lost_white.png"),
	ic_non_responsive_white: require("@/assets/ic_non_responsive_white.png"),
	ic_waiting_list_white: require("@/assets/ic_waiting_list_white.png"),
	ic_send_white: require("@/assets/ic_send_white.png"),

	ic_warning_status: require("@/assets/ic_warning_status.png"),
	ic_success_status: require("@/assets/ic_success_status.png"),
	ic_info_status: require("@/assets/ic_info_status.png"),
	ic_error_status: require("@/assets/ic_error_status.png"),


	// nav
	ic_beta_nav: require("@/assets/nav/ic_beta_nav.png"),
	ic_billing_nav: require("@/assets/nav/ic_billing_nav.png"),
	ic_calendar_nav: require("@/assets/nav/ic_calendar_nav.png"),
	ic_camp_setup_nav: require("@/assets/nav/ic_camp_setup_nav.png"),
	ic_cc_leads_nav: require("@/assets/nav/ic_cc_leads_nav.png"),
	ic_contacts_nav: require("@/assets/nav/ic_contacts_nav.png"),
	ic_edocs_nav: require("@/assets/nav/ic_edocs_nav.png"),
	ic_events_nav: require("@/assets/nav/ic_events_nav.png"),
	ic_group_leads_nav: require("@/assets/nav/ic_group_leads_nav.png"),
	ic_donations_nav: require("@/assets/nav/ic_donations_nav.png"),
	ic_onboarding_nav: require("@/assets/nav/ic_onboarding_nav.png"),
	ic_pricing_nav: require("@/assets/nav/ic_pricing_nav.png"),
	ic_settings_nav: require("@/assets/nav/ic_settings_nav.png"),
	ic_user_profile_nav: require("@/assets/nav/ic_user_profile_nav.png"),
	ic_widgets_nav: require("@/assets/nav/ic_widgets_nav.png"),
	ic_support_nav: require("@/assets/nav/ic_support_nav.png"),
	ic_switch_account_nav: require("@/assets/nav/ic_switch_account_nav.png"),

	ic_camp_nav: require("@/assets/nav/ic_camp_nav.png"),
	ic_camp_map_nav: require("@/assets/nav/ic_camp_map_nav.png"),
	ic_media_nav: require("@/assets/nav/ic_media_nav.png"),
	ic_messages_nav: require("@/assets/nav/ic_messages_nav.png"),
	ic_itinerary_nav: require("@/assets/nav/ic_itinerary_nav.png"),
	ic_group_registration_nav: require("@/assets/nav/ic_group_registration_nav.png"),
	ic_teams_nav: require("@/assets/nav/ic_teams_nav.png"),
	ic_feature_request_nav: require("@/assets/nav/ic_feature_request_nav.png"),


	//Rei Spreadsheets
	ic_contact_book: require("@/assets/ic_contact_book.png"),
	ic_groups: require("@/assets/ic_groups.png"),

	//Rei Campstore
	ic_campstore_nav: require("@/assets/nav/ic_campstore_nav.png"),
	ic_cashier: require("@/assets/ic_cashier.png"),
	ic_manage: require("@/assets/ic_manage.png"),
	ic_cart: require("@/assets/ic_cart.png"),
	ic_wallet: require("@/assets/ic_wallet.png"),
	ic_facescan: require("@/assets/ic_facescan.png"),
	ic_add_face: require("@/assets/ic_add_face.png"),

	//rei import Support ASSETS
	ic_submit_ticket: require("@/assets/ic_submit_ticket.png"),
	ic_training_videos: require("@/assets/ic_training_videos.png"),
	ic_help_docs: require("@/assets/ic_help_docs.png"),
	ic_no_recording: require("@/assets/ic_no_recording.png"),
	ic_with_recording: require("@/assets/ic_with_recording.png"),
	ic_thank_you: require("@/assets/ic_thank_you.png"),
	ic_logout: require("@/assets/ic_logout.png"),
	ic_upload_image: require("@/assets/ic_upload_image.png"),
	ic_send_arrow_blue: require("@/assets/ic_send_arrow_blue.png"),
	ic_logo_black: require("@/assets/ic_logo_black.png"),


	//Rei RV And TENT Import
	ic_rv: require("@/assets/ic_rv.png"),
	ic_chevron_left: require("@/assets/ic_chevron_left.png"),
	ic_chevron_right: require("@/assets/ic_chevron_right.png"),

	//arnold import
	th_kitchen: require("@/assets/th_kitchen.png"),
	th_3day: require("@/assets/th_3day.png"),
	th_squadMaintenance: require("@/assets/th_squadMaintenance.png"),
	th_squadMaintenanceRequest: require("@/assets/th_squadMaintenanceRequest.png"),
	th_squadMaintenanceSelect: require("@/assets/th_squadSelect.png"),
	th_squadMem: require("@/assets/th_squadMem.png"),
	th_dm_chat: require("@/assets/th_dm_chat.png"),
	th_squad_chat: require("@/assets/th_squad_chat.png"),
	th_note: require("@/assets/th_note.png"),
	th_verse: require("@/assets/th_verse.png"),
	ic_user_image: require("@/assets/ic_user_image.png"),
	ic_clean: require("@/assets/ic_clean.png"),
	ic_room_cleaning: require("@/assets/ic_room_cleaning.png"),
	ic_room_assignment: require("@/assets/ic_room_assignment.png"),
	ic_send_2: require("@/assets/ic_send_2.png"),
	ic_user_profile: require("@/assets/ic_user_profile.png"),
	ic_user_group: require("@/assets/ic_user_group.png"),
	ic_paper_clip: require("@/assets/ic_paper_clip.png"),
	ic_close_arrow: require("@/assets/ic_close_arrow.png"),
	ic_open_arrow: require("@/assets/ic_open_arrow.png"),
	ic_channel_home: require("@/assets/ic_channel_home.png"),
	ic_add_channel: require("@/assets/ic_add_channel.png"),
	ic_channel_arrow: require("@/assets/ic_channel_arrow.png"),
	ic_chat_zoom: require("@/assets/ic_chat_zoom.png"),
	ic_note_back: require("@/assets/ic_note_back.png"),
	ic_note_share: require("@/assets/ic_note_share.png"),
	ic_note_pin: require("@/assets/ic_note_pin.png"),
	ic_note_delete_red: require("@/assets/ic_note_delete_red.png"),
	ic_verse_icon: require("@/assets/ic_verse.png"),



	// camp map
	ic_toilet: require("@/assets/ic_toilet.png"),
	ic_storage: require("@/assets/ic_storage.png"),
	ic_shower: require("@/assets/ic_shower.png"),
	ic_office_building: require("@/assets/ic_office_building.png"),
	ic_meeting_room: require("@/assets/ic_meeting_room.png"),
	ic_housing: require("@/assets/ic_housing.png"),
	ic_fountain: require("@/assets/ic_fountain.png"),
	ic_dining: require("@/assets/ic_dining.png"),
	ic_conference: require("@/assets/ic_conference.png"),
	ic_conference_people: require("@/assets/ic_conference_people.png"),
	ic_comfort_room: require("@/assets/ic_comfort_room.png"),
	ic_bonfire: require("@/assets/ic_bonfire.png"),
	ic_bed: require("@/assets/ic_bed.png"),

	//master track
	ic_participants: require("@/assets/ic_participants.png"),
	ic_custom: require("@/assets/ic_custom_activity.png"),
	ic_time: require("@/assets/ic_mdi_clock.png"),
	ic_capacity: require("@/assets/ic_capacity.png"),
	ic_leaders_click: require("@/assets/ic_leaders_click.png"),
	ic_leaders: require("@/assets/ic_leaders.png"),
	ic_members_click: require("@/assets/ic_members_click.png"),
	ic_members: require("@/assets/ic_members.png"),
	ic_itinerary_click: require("@/assets/ic_itinerary_click.png"),
	ic_itinerary2: require("@/assets/ic_itinerary2.png"),

	//maintenance request
	ic_wrench: require("@/assets/ic_wrench.png"),
	ic_addBtn: require("@/assets/ic_addBtnFr.png"),
	ic_chevronleft: require("@/assets/ic_chevronleft.png"),
	ic_foundation: require("@/assets/ic_foundation.png"),
	ic_chevron_left_white: require("@/assets/ic_chevron_left_white.png"),
	ic_circle_check_fill: require('@/assets/ic_check_greenfill.png'),
	ic_circle_check: require('@/assets/ic_check_reg.png'),
	ic_medication: require('@/assets/ic_medication.png'),
	ic_chaticon: require('@/assets/ic_chaticon.png'),
	ic_attach: require('@/assets/ic_attach.png'),
	ic_sendgizmo: require('@/assets/ic_send.png'),
	ic_maximize2: require('@/assets/ic_maximize2.png'),
	ic_googletrans: require('@/assets/ic_googletrans.png'),

	ic_closegizmo: require('@/assets/ic_closeModal.png'),
	ic_attachimg: require('@/assets/ic_attachimg.png'),
	ic_nosale: require('@/assets/ic_nosale.png'),



	// thumbnails
	th_clock_widget: require("@/assets/th_clock_widget.png"),
	th_clock_half_widget: require("@/assets/th_clock_half_widget.png"),
	th_clock_full_widget: require("@/assets/th_clock_full_widget.png"),
	th_notes_widget: require("@/assets/th_notes_widget.png"),
	th_bible_verse_widget: require("@/assets/th_bible_verse_widget.png"),
	th_weather_widget: require("@/assets/th_weather_widget.png"),
	th_finances_monthly_status_full_widget: require("@/assets/th_finances_monthly_status_full_widget.png"),
	th_finances_min_vs_actual_status_full_widget: require("@/assets/th_finances_min_vs_actual_widget.png"),
	th_finances_percent_vs_actual_status_full_widget: require("@/assets/th_finances_percent_vs_actual_widget.png"),
	th_housing_quarter_widget: require("@/assets/th_housing_quarter_widget.png"),
	th_housing_half_widget: require("@/assets/th_housing_half_widget.png"),
	th_housing_full_widget: require("@/assets/th_housing_full_widget.png"),
	th_task_widget: require("@/assets/th_task_widget.jpg"),

	th_groupsales_quarter_a_widget: require("@/assets/th_groupsales_quarter_a_widget.png"),
	th_groupsales_quarter_b_widget: require("@/assets/th_groupsales_quarter_b_widget.png"),
	th_groupsales_quarter_c_widget: require("@/assets/th_groupsales_quarter_c_widget.png"),
	th_groupsales_quarter_d_widget: require("@/assets/th_groupsales_quarter_d_widget.png"),
	th_groupsales_full_a_widget: require("@/assets/th_groupsales_full_a_widget.png"),
	th_groupsales_full_b_widget: require("@/assets/th_groupsales_full_b_widget.png"),
	th_groupsales_half_a_widget: require("@/assets/th_groupsales_half_a_widget.png"),
	th_groupsales_half_b_widget: require("@/assets/th_groupsales_half_b_widget.png"),

	th_communication_guestinquiries_full_a_widget: require("@/assets/th_communication_guestinquiries_full_a_widget.png"),
	th_communication_privatemessages_full_a_widget: require("@/assets/th_communication_privatemessages_full_a_widget.png"),
	th_communication_teamchat_full_a_widget: require("@/assets/th_communication_teamchat_full_a_widget.png"),
	th_program_medication_full_widget: require('@/assets/th_medications.png'),

	th_donors_recentdonations: require("@/assets/th_RecentDonations.png"),
	th_donors_overallstat: require("@/assets/th_donors_overallstat.png"),
	th_donors_visitation: require("@/assets/th_donors_notifications.png"),
	th_crashed_widget: require("@/assets/th_crashed_widget.png"),
	// draggable preview
	dr_groupsales_quarter_a_widget: require("@/assets/draggable/dr_groupsales_quarter_a_widget.png"),

	bg_white:
		"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSdjZeWY5FKTn2E8vz8ISx7Dh816GAnSKN44P2H_lhHEw&s",
	bg_abstract_1: require("@/assets/landingpage/br_abstract_1.png"),
}

export const CamperGroupStagesIcons = {
	Inquired: Images["ic_inquired_stage"],
	Contacted: Images["ic_contacted_stage"],
	Communicating: Images["ic_communicating_stage"],
	"Contract Sent": Images["ic_contract_sent_stage"],
	"Contract Signed": Images["ic_contract_signed_stage"],
	Booked: Images["ic_booked_stage"],
	"Non-Responsive": Images["ic_non_responsive_stage"],
	"Waiting List": Images["ic_waiting_list_stage"],
	"No Sale": Images["ic_nosale"]
}
export const CamperGroupStagesWhite: Record<string, string> = {
	Inquired: Images["ic_inquired_white"],
	Contacted: Images["ic_contacted_white"],
	Communicating: Images["ic_communicating_white"],
	"Contract Sent": Images["ic_contract_sent_white"],
	"Contract Signed": Images["ic_contract_signed_white"],
	Booked: Images["ic_booked_white"],
	"Non-Responsive": Images["ic_non_responsive_white"],
	"Waiting List": Images["ic_waiting_list_white"],
	"No Sale": Images["ic_waiting_list_white"],
}
export default Images
